# Generated by Django 5.2 on 2025-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='expertise',
            field=models.CharField(default='general', max_length=255),
            preserve_default=False,
        ),
    ]
