# Generated by Django 5.2 on 2025-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_authorprofile_achievements_authorprofile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
