# Generated by Django 5.2 on 2025-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_authorprofile_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='fiction', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
